version: '3'

services:
  api:
    image: shreyanshtomar/moderation_api:1.0
    restart: always
    volumes: ['./server:/server']
    networks:
      rocketchat:
        aliases:
          - moderation-api
    environment:
      - RC_UUID=8BvRqoZqbw7BGEW3p #Rocket Chat Admin's User-ID
      - RC_TOKEN=0JoMTmwykFBkiTeKtjphATkUwOGC3OSiuyn0iDRSy4T #Rocket Chat Admin's Authentication Token
  
networks:
  rocketchat:
    driver: bridge
