version: '3'

services:

  api:
    container_name: moderation_api
    restart: always
    build: ./server
    volumes: ['./server:/server']
    expose:
      - "5000"
    ports:
      - "5000:5000"
    network_mode: "host"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    expose:
      - "8080"
    ports:
      - "80:8080"
    network_mode: "host"
